'''CancellationException - an exception raised because a task was cancelled

'''

class CancellationException(Exception):
    pass
